### ISSUE TITLE
Can you help enabling Proxy Enabled on the Task for Enterprise users ?

### ISSUE THREAD

**Issue by vinaysandela** [sonatype-nexus-community/iq-github-action#5]
We are using the Task to Scan on our NexusIQ Scan using Self-Hosted Linux Action Runner.  The container it creates from the workflow isn't reaching our NexusIQ. We were getting below error -
[INFO] I/O exception (java.net.NoRouteToHostException) caught when processing request to {s}->[https://<<nexusiqurl>>:443:](<<nexusiqurl>>) No route to host (Host unreachable)

As workaround, with NexusIQ being our Enterprise level tool, we added a Proxy field and that fixed the issues.  Can you please help having that option to this public task too. Thanks

```
    - name: Nexus IQ Policy Evaluation
      uses: sonatype-nexus-community/iq-github-action@master
      with:
        serverUrl: <<nexusiqurl>>
        username: ${{ secrets.uname }}
        password: ${{ secrets.pword }}
        applicationId: <<AppID>>
        stage: Build
        target: /application/target
        proxy: <<Proxy>>    ------We need this to be added. 
```
Forked and tested this task  - https://github.com/Sandelas/nexus-iq-task-fork
